### ISSUE TITLE
Communication Dish Keycard not in game via creative menu

### ISSUE THREAD

**Issue by spartainman64** [MJRLegends/Planet-Progression#70] opened 2020-05-17 06:20 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** Yes.

### Description of Issue:
There is no "Communications Dish Keycard".

### Steps to Reproduce Issue
1. Launch game.
2. Search for keycard.
3. Find out that there is no keycard.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself. See below on how to get them]
> *How do i locate a crash log* see https://docs.mjrlegends.com/General%20Minecraft/crash-log/

**Screenshots (if applicable):** 
https://gyazo.com/9d726323a474fc79e776f5f486e3c3c6

**Version of Mod using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.12.2 - 0.4.4
**Where did this bug happen:** [Single Player or Server]
Single Player
### Additional Information
[Any other information that may be able to help me with the problem]

**Comment by pitris90** [comment] 2020-05-27 18:05
I have this issue too... Communication Dish Keycard just isn't in the game or at least i can't find it too. I play on the server and I have 0.4.4 version too.

**Comment by MJRLegends** [comment] 2020-05-28 00:36
Can you send me a copy of your config please

**Comment by pitris90** [comment] 2020-05-28 14:04
I have more info now. The recipe has been shown to someone on our server somehow and when we wanted to craft it, it was normally craftable. Problem is that some of us really can't see it in JEI or even in Creative Tab... 
![2020-05-28_16 04 24](https://user-images.githubusercontent.com/37505379/83151483-ead12800-a0fc-11ea-90a4-67b80fcfb4af.png)

**Comment by MJRLegends** [comment] 2020-05-28 19:50
Has who ever made the mod pack hidden the item in jei?

**Comment by pitris90** [comment] 2020-05-28 22:57
I didn't hide anything in JEI (this is my custom modpack). But as i said, I can't see that keycard in creative tab either as my friend. But second friend could see it normally and we discovered thanks to him crafting recipe and my frined was able to craft it. Its weird at least for me.

**Comment by MJRLegends** [comment] 2020-05-29 21:26
The JEI and creative tabs is a different issue, its not showing in creative tabs as i didnt set it up to do that. As for JEI i cant reproduce your issue there it shows for me

**Comment by MJRLegends** [comment] 2020-05-29 21:42
![](https://i.gyazo.com/ae656e2149bc9ad8725d6b910d476432.png)

**Comment by MJRLegends** [comment] 2020-05-29 21:43
I will fix the creative tab thing that i can fix but the JEI thing idk it doesnt seem to be my issue..

**Comment by MJRLegends** [comment] 2020-05-29 21:44
Does the Satellite Controller say you need a keycard?

**Comment by pitris90** [comment] 2020-05-30 02:53
Maybe I found a problem... In JEI I had enabled NEI Item Panel and NEI Search Bar... when I switched back to JEI, I can see keycard now
![2020-05-30_04 53 37](https://user-images.githubusercontent.com/37505379/83318042-9085b380-a231-11ea-9058-55aabaa96f9e.png)

**Comment by MJRLegends** [comment] 2020-05-30 11:16
Sounds like a bug with that feature in that mod, maybe report it to them?

**Comment by MJRLegends** [comment] 2020-05-30 11:17
The fact its not in the creative menu will be fixed in next update

**Closed** 2020-07-12 01:56 UTC
Labels: 1.10.2, 1.11.2, 1.12.2, 1.8.9, bug, fixed in next update(will close when update out)
